import 'package:audioplayers/audioplayers.dart';

import 'game_data_manager.dart';

/// Plays the game's short sound effects. Honors the user's "Sound effects"
/// setting via [GameDataManager.soundEnabled]. Assets are generated by
/// tool/generate_sfx.py and bundled under assets/sounds/.
class SoundService {
  static final SoundService _instance = SoundService._internal();
  factory SoundService() => _instance;
  SoundService._internal();

  // AssetSource paths are relative to the `assets/` folder.
  static const String _tap = 'sounds/tap.wav';
  static const String _connect = 'sounds/connect.wav';
  static const String _win = 'sounds/win.wav';
  static const String _error = 'sounds/error.wav';

  final Map<String, AudioPlayer> _players = {};
  bool _initialized = false;

  Future<void> init() async {
    if (_initialized) return;
    _initialized = true;
    for (final asset in [_tap, _connect, _win, _error]) {
      try {
        final player = AudioPlayer();
        await player.setReleaseMode(ReleaseMode.stop);
        await player.setPlayerMode(PlayerMode.lowLatency);
        // Pre-cache the source so the first play has minimal latency.
        await player.setSource(AssetSource(asset));
        _players[asset] = player;
      } catch (_) {
        // Audio is non-essential; ignore failures (e.g. unsupported platform).
      }
    }
  }

  bool get _enabled => GameDataManager().soundEnabled;

  Future<void> _play(String asset) async {
    if (!_enabled) return;
    final player = _players[asset];
    if (player == null) return;
    try {
      await player.stop();
      await player.play(AssetSource(asset));
    } catch (_) {
      // Swallow playback errors so gameplay is never interrupted.
    }
  }

  void playTap() => _play(_tap);
  void playConnect() => _play(_connect);
  void playWin() => _play(_win);
  void playError() => _play(_error);

  Future<void> dispose() async {
    for (final player in _players.values) {
      await player.dispose();
    }
    _players.clear();
    _initialized = false;
  }
}
